FROM barichello/godot-ci:4.2.1 AS builder
WORKDIR /app

COPY godot/ .

RUN mkdir -p /app/build
RUN godot --headless --export-release "Linux/X11" /app/build/mi_juego.x86_64

FROM nginx:stable-alpine

COPY --from=builder /app/build/mi_juego.x86_64 /usr/share/nginx/html/downloads/mi_juego.x86_64

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
